-- Migração para instalações existentes: substitui a conexão PostgreSQL direta pela Data API.
-- Execute uma vez no SQL Editor do Supabase antes de iniciar o painel.
-- O Streamlit acessa somente as funções públicas abaixo pela Data API.
-- Este arquivo é uma fotografia histórica. Instalações novas devem executar o
-- sql/adiantamento_meta.sql atual, que já contém as cinco contas editoras.
begin;

create schema if not exists comercial_marts;

-- Estado corrente: uma linha por competência e região.
create table if not exists comercial_marts.campanha_polar_adiantamento (
    competencia date not null,
    regiao text not null check (regiao <> '' and regiao = trim(regiao)),
    semana_1_32 boolean not null default false,
    semana_2_56 boolean not null default false,
    semana_3_80 boolean not null default false,
    observacao text not null default '' check (length(observacao) <= 2000),
    versao integer not null check (versao > 0),
    atualizado_em timestamptz not null,
    atualizado_por text not null check (atualizado_por in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech')),
    usuario_id text not null check (usuario_id <> ''),
    primary key (competencia, regiao),
    check (competencia = date_trunc('month', competencia)::date),
    check (competencia >= date '2026-09-01' and competencia <= date '2026-12-01')
);

-- Trilha imutável: uma linha por versão salva.
create table if not exists comercial_marts.campanha_polar_adiantamento_historico (
    id integer generated by default as identity primary key,
    competencia date not null,
    regiao text not null,
    versao integer not null,
    anterior jsonb,
    novo jsonb not null,
    alterado_em timestamptz not null,
    alterado_por text not null check (alterado_por in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech')),
    usuario_id text not null,
    unique (competencia, regiao, versao)
);

-- Mantém as duas contas editoras também em instalações que receberam a versão anterior.
alter table comercial_marts.campanha_polar_adiantamento
    drop constraint if exists campanha_polar_adiantamento_atualizado_por_check;
alter table comercial_marts.campanha_polar_adiantamento
    add constraint campanha_polar_adiantamento_atualizado_por_check
    check (atualizado_por in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech'));
alter table comercial_marts.campanha_polar_adiantamento_historico
    drop constraint if exists campanha_polar_adiantamento_historico_alterado_por_check;
alter table comercial_marts.campanha_polar_adiantamento_historico
    add constraint campanha_polar_adiantamento_historico_alterado_por_check
    check (alterado_por in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech'));

alter table comercial_marts.campanha_polar_adiantamento enable row level security;
alter table comercial_marts.campanha_polar_adiantamento_historico enable row level security;
revoke all on comercial_marts.campanha_polar_adiantamento from public, anon, authenticated;
revoke all on comercial_marts.campanha_polar_adiantamento_historico from public, anon, authenticated;
revoke all on sequence comercial_marts.campanha_polar_adiantamento_historico_id_seq from public, anon, authenticated;

-- RPC de leitura: deriva a lista de regiões das metas positivas e combina os
-- checks persistidos, sem expor as tabelas diretamente.
create or replace function public.campanha_polar_carregar_adiantamento(p_competencia date)
returns table (
    regiao text,
    "time" text,
    meta numeric,
    semana_1_32 boolean,
    semana_2_56 boolean,
    semana_3_80 boolean,
    observacao text,
    versao integer,
    atualizado_em timestamptz,
    atualizado_por text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
    if (select auth.uid()) is null then
        raise exception 'AUTH_REQUIRED' using errcode = '42501';
    end if;
    if p_competencia is null
       or p_competencia <> date_trunc('month', p_competencia)::date
       or extract(year from p_competencia) <> 2026
       or extract(month from p_competencia) not in (9, 10, 11, 12) then
        raise exception 'INVALID_MONTH' using errcode = '22023';
    end if;

    return query
    with metas as (
        select
            trim(m.regiao)::text as regiao_meta,
            case
                when count(distinct upper(trim(m.time))) = 1 then min(trim(m.time))::text
                else 'Múltiplos times'::text
            end as time_meta,
            sum(m.meta)::numeric as valor_meta
        from comercial_marts.metas_comerciais as m
        where m.data = p_competencia
          and m.meta > 0
          and m.regiao is not null
          and trim(m.regiao) <> ''
          and upper(trim(m.time)) in ('CANAIS', 'TIME NORTE', 'TIME SUL')
        group by trim(m.regiao)
    )
    select
        mt.regiao_meta,
        mt.time_meta,
        mt.valor_meta,
        coalesce(a.semana_1_32, false),
        coalesce(a.semana_2_56, false),
        coalesce(a.semana_3_80, false),
        coalesce(a.observacao, ''),
        coalesce(a.versao, 0),
        a.atualizado_em,
        coalesce(a.atualizado_por, '')
    from metas as mt
    left join comercial_marts.campanha_polar_adiantamento as a
      on a.competencia = p_competencia
     and a.regiao = mt.regiao_meta
    order by mt.regiao_meta;
end;
$$;

-- RPC de escrita mensal: autoriza pelo JWT, valida o lote inteiro, compara a
-- versão corrente e grava estado + histórico na mesma transação.
create or replace function public.campanha_polar_salvar_adiantamento(
    p_competencia date,
    p_registros jsonb
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_email text := lower(trim(coalesce((select auth.jwt()) ->> 'email', '')));
    v_usuario_id uuid := (select auth.uid());
    v_item jsonb;
    v_regiao text;
    v_observacao text;
    v_versao_enviada integer;
    v_versao_atual integer;
    v_anterior comercial_marts.campanha_polar_adiantamento%rowtype;
    v_existe boolean;
    v_valores_anteriores jsonb;
    v_valores_novos jsonb;
    v_agora timestamptz;
    v_alterados integer := 0;
begin
    if v_usuario_id is null then
        raise exception 'AUTH_REQUIRED' using errcode = '42501';
    end if;
    if v_email not in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech') then
        raise exception 'PERMISSION_DENIED' using errcode = '42501';
    end if;
    if p_competencia is null
       or p_competencia <> date_trunc('month', p_competencia)::date
       or extract(year from p_competencia) <> 2026
       or extract(month from p_competencia) not in (9, 10, 11, 12) then
        raise exception 'INVALID_MONTH' using errcode = '22023';
    end if;
    if jsonb_typeof(p_registros) is distinct from 'array' then
        raise exception 'INVALID_ROWS' using errcode = '22023';
    end if;
    if exists (
        select 1
        from jsonb_array_elements(p_registros) as elemento(valor)
        group by elemento.valor ->> 'regiao'
        having count(*) > 1
    ) then
        raise exception 'INVALID_DUPLICATE_REGION' using errcode = '22023';
    end if;

    -- Valida o lote inteiro antes de iniciar as gravações.
    for v_item in select value from jsonb_array_elements(p_registros)
    loop
        if jsonb_typeof(v_item) is distinct from 'object'
           or jsonb_typeof(v_item -> 'regiao') is distinct from 'string'
           or jsonb_typeof(v_item -> 'semana_1_32') is distinct from 'boolean'
           or jsonb_typeof(v_item -> 'semana_2_56') is distinct from 'boolean'
           or jsonb_typeof(v_item -> 'semana_3_80') is distinct from 'boolean'
           or jsonb_typeof(v_item -> 'observacao') is distinct from 'string'
           or jsonb_typeof(v_item -> 'versao') is distinct from 'number'
           or (v_item ->> 'versao') !~ '^[0-9]+$' then
            raise exception 'INVALID_ROW' using errcode = '22023';
        end if;

        v_regiao := v_item ->> 'regiao';
        v_observacao := v_item ->> 'observacao';
        if v_regiao = '' or v_regiao <> trim(v_regiao) or length(v_observacao) > 2000 then
            raise exception 'INVALID_ROW' using errcode = '22023';
        end if;
        if not exists (
            select 1
            from comercial_marts.metas_comerciais as m
            where m.data = p_competencia
              and m.meta > 0
              and trim(m.regiao) = v_regiao
              and upper(trim(m.time)) in ('CANAIS', 'TIME NORTE', 'TIME SUL')
        ) then
            raise exception 'INVALID_REGION' using errcode = '22023';
        end if;
    end loop;

    for v_item in select value from jsonb_array_elements(p_registros)
    loop
        v_regiao := v_item ->> 'regiao';
        v_observacao := v_item ->> 'observacao';
        v_versao_enviada := (v_item ->> 'versao')::integer;
        v_valores_novos := jsonb_build_object(
            'semana_1_32', (v_item ->> 'semana_1_32')::boolean,
            'semana_2_56', (v_item ->> 'semana_2_56')::boolean,
            'semana_3_80', (v_item ->> 'semana_3_80')::boolean,
            'observacao', v_observacao
        );

        select *
        into v_anterior
        from comercial_marts.campanha_polar_adiantamento as a
        where a.competencia = p_competencia and a.regiao = v_regiao
        for update;
        v_existe := found;

        if v_existe then
            v_versao_atual := v_anterior.versao;
        else
            v_versao_atual := 0;
        end if;

        if v_versao_enviada <> v_versao_atual then
            raise exception 'CONCURRENT_CHANGE' using errcode = '40001';
        end if;

        if v_existe then
            v_valores_anteriores := jsonb_build_object(
                'semana_1_32', v_anterior.semana_1_32,
                'semana_2_56', v_anterior.semana_2_56,
                'semana_3_80', v_anterior.semana_3_80,
                'observacao', v_anterior.observacao
            );
            if v_valores_anteriores = v_valores_novos then
                continue;
            end if;
        else
            v_valores_anteriores := null;
        end if;

        v_agora := clock_timestamp();
        if v_existe then
            update comercial_marts.campanha_polar_adiantamento
            set semana_1_32 = (v_item ->> 'semana_1_32')::boolean,
                semana_2_56 = (v_item ->> 'semana_2_56')::boolean,
                semana_3_80 = (v_item ->> 'semana_3_80')::boolean,
                observacao = v_observacao,
                versao = v_anterior.versao + 1,
                atualizado_em = v_agora,
                atualizado_por = v_email,
                usuario_id = v_usuario_id::text
            where competencia = p_competencia
              and regiao = v_regiao
              and versao = v_anterior.versao;
            if not found then
                raise exception 'CONCURRENT_CHANGE' using errcode = '40001';
            end if;
        else
            insert into comercial_marts.campanha_polar_adiantamento (
                competencia, regiao, semana_1_32, semana_2_56, semana_3_80,
                observacao, versao, atualizado_em, atualizado_por, usuario_id
            ) values (
                p_competencia, v_regiao,
                (v_item ->> 'semana_1_32')::boolean,
                (v_item ->> 'semana_2_56')::boolean,
                (v_item ->> 'semana_3_80')::boolean,
                v_observacao, 1, v_agora, v_email, v_usuario_id::text
            );
        end if;

        insert into comercial_marts.campanha_polar_adiantamento_historico (
            competencia, regiao, versao, anterior, novo,
            alterado_em, alterado_por, usuario_id
        ) values (
            p_competencia, v_regiao,
            case when v_existe then v_anterior.versao + 1 else 1 end,
            v_valores_anteriores, v_valores_novos,
            v_agora, v_email, v_usuario_id::text
        );
        v_alterados := v_alterados + 1;
    end loop;

    return v_alterados;
exception
    when unique_violation then
        raise exception 'CONCURRENT_CHANGE' using errcode = '40001';
end;
$$;

-- RPC da campanha: separa o payload por mês e reutiliza a função mensal; uma
-- falha em qualquer competência provoca rollback de todo o lote.
create or replace function public.campanha_polar_salvar_adiantamento_campanha(
    p_registros jsonb
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_competencia_texto text;
    v_registros_mes jsonb;
    v_alterados_mes integer;
    v_alterados_total integer := 0;
begin
    if (select auth.uid()) is null then
        raise exception 'AUTH_REQUIRED' using errcode = '42501';
    end if;
    if jsonb_typeof(p_registros) is distinct from 'array' then
        raise exception 'INVALID_ROWS' using errcode = '22023';
    end if;
    if exists (
        select 1
        from jsonb_array_elements(p_registros) as elemento(valor)
        where jsonb_typeof(elemento.valor -> 'competencia') is distinct from 'string'
           or elemento.valor ->> 'competencia' not in (
                '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01'
           )
    ) then
        raise exception 'INVALID_MONTH' using errcode = '22023';
    end if;
    if exists (
        select 1
        from jsonb_array_elements(p_registros) as elemento(valor)
        group by elemento.valor ->> 'competencia', elemento.valor ->> 'regiao'
        having count(*) > 1
    ) then
        raise exception 'INVALID_DUPLICATE_REGION' using errcode = '22023';
    end if;

    for v_competencia_texto in
        select distinct elemento.valor ->> 'competencia'
        from jsonb_array_elements(p_registros) as elemento(valor)
        order by 1
    loop
        select coalesce(jsonb_agg(elemento.valor - 'competencia'), '[]'::jsonb)
        into v_registros_mes
        from jsonb_array_elements(p_registros) as elemento(valor)
        where elemento.valor ->> 'competencia' = v_competencia_texto;

        select public.campanha_polar_salvar_adiantamento(
            v_competencia_texto::date,
            v_registros_mes
        ) into v_alterados_mes;
        v_alterados_total := v_alterados_total + coalesce(v_alterados_mes, 0);
    end loop;

    return v_alterados_total;
end;
$$;

revoke all privileges on function public.campanha_polar_carregar_adiantamento(date) from public, anon;
revoke all privileges on function public.campanha_polar_salvar_adiantamento(date, jsonb) from public, anon;
revoke all privileges on function public.campanha_polar_salvar_adiantamento_campanha(jsonb) from public, anon;
grant execute on function public.campanha_polar_carregar_adiantamento(date) to authenticated;
grant execute on function public.campanha_polar_salvar_adiantamento(date, jsonb) to authenticated;
grant execute on function public.campanha_polar_salvar_adiantamento_campanha(jsonb) to authenticated;

commit;
