-- Execute uma vez no PostgreSQL/Supabase antes de iniciar o painel.
-- As tabelas são mantidas pelo aplicativo; não devem ser reconstruídas pelo dataflow.
begin;
create schema if not exists comercial_marts;

create table if not exists comercial_marts.campanha_polar_adiantamento (
    competencia date not null,
    regiao text not null check (regiao <> '' and regiao = trim(regiao)),
    semana_1_32 boolean not null default false,
    semana_2_56 boolean not null default false,
    semana_3_80 boolean not null default false,
    observacao text not null default '' check (length(observacao) <= 2000),
    versao integer not null check (versao > 0),
    atualizado_em timestamptz not null,
    atualizado_por text not null check (atualizado_por in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech')),
    usuario_id text not null check (usuario_id <> ''),
    primary key (competencia, regiao),
    check (competencia = date_trunc('month', competencia)::date),
    check (competencia >= date '2026-09-01' and competencia <= date '2026-12-01')
);

create table if not exists comercial_marts.campanha_polar_adiantamento_historico (
    id integer generated by default as identity primary key,
    competencia date not null,
    regiao text not null,
    versao integer not null,
    anterior jsonb,
    novo jsonb not null,
    alterado_em timestamptz not null,
    alterado_por text not null check (alterado_por in ('lais.vendrasco@ambar.tech', 'leonardo.watanabe@ambar.tech')),
    usuario_id text not null,
    unique (competencia, regiao, versao)
);

-- O aplicativo usa conexão privada de servidor, não chaves públicas da API.
-- Sem políticas RLS, clientes públicos/autenticados da API não acessam as tabelas.
alter table comercial_marts.campanha_polar_adiantamento enable row level security;
alter table comercial_marts.campanha_polar_adiantamento_historico enable row level security;
revoke all on comercial_marts.campanha_polar_adiantamento from public, anon, authenticated;
revoke all on comercial_marts.campanha_polar_adiantamento_historico from public, anon, authenticated;
revoke all on sequence comercial_marts.campanha_polar_adiantamento_historico_id_seq from public, anon, authenticated;
commit;
